//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Credits
    {
        public int Id { get; set; }
        public Nullable<int> ApplicationId { get; set; }
        public Nullable<decimal> InitialPayment { get; set; }
        public Nullable<int> Months { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<decimal> MonthlyPayment { get; set; }
        public Nullable<bool> Approved { get; set; }
    
        public virtual Applications Applications { get; set; }
    }
}
